/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdr.vue;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import jdr.modele.Classe;
import jdr.modele.Personnage;


/**
 *
 * @author mathi
 */
public class MenClasse extends javax.swing.JFrame implements IDescriptionClasse{
   String choix = CLASSEDESLIENS[0];
   Personnage personnage ;
   
    /**
     * Creates new form MenClasse
     */
    public MenClasse() {
        initComponents();
    }

     public MenClasse(Personnage p) {
        initComponents();
 
        this.personnage=p;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitre = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelimage = new javax.swing.JLabel();
        jButtonChoisir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitre.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        jLabeltitre.setForeground(new java.awt.Color(102, 102, 0));
        jLabeltitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltitre.setText("Les Classes");
        jLabeltitre.setToolTipText("");
        jPanel1.add(jLabeltitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 540, 90));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barbare", "Barde", "Druide", "Ensorceleur", "Guerrier", "Magicien", "Moine", "Paladin", "Prêtre", "Rôdeur", "Roublard" }));
        jComboBox1.addActionListener(new ItemAction());
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 70));

        jLabelimage.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Barde.jpg"))); // NOI18N
        jPanel1.add(jLabelimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 290, 400));

        jButtonChoisir.setText("choisir");
        jButtonChoisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoisirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChoisir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 60));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoisirActionPerformed
        for (int i = 0; i < ClasseTab.length; i++) {
            System.out.println(choix + " rfr"+ ClasseTab[i].getNom()  + " =" + ClasseTab[i].getNom().trim().equalsIgnoreCase(choix.trim()));
           if(ClasseTab[i].getNom().trim().equalsIgnoreCase(choix.trim())){
              
               personnage.setClasse(ClasseTab[i]);
               System.out.println("jdr.vue.MenClasse.jButtonChoisirActionPerformed()" + "test");
               MenuReligion suite = new MenuReligion(personnage);
               suite.setVisible(true);
               dispose();
               
           }else{
               System.out.println("jdr.vue.MenClasse.jButtonChoisirActionPerformed()");
           }
            
        }
        
    }//GEN-LAST:event_jButtonChoisirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenClasse().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoisir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


class ItemAction implements ActionListener{
    public void actionPerformed(ActionEvent e) {
    
     choix = jComboBox1.getSelectedItem().toString();
         System.out.println("ActionListener : action sur " + choix);
         
        for (int i = 0; i < CLASSEDESLIENS.length; i++) {
            
           if(CLASSEDESLIENS[i].equalsIgnoreCase(choix)){
              jTextArea1.setText(CLASSEDESLIENS[i+1]);
              
              jLabelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource(CLASSEDESLIENS[i+2])));

                    
           }
            
        }
    }               
  }



}
