/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdr.vue;


import javax.swing.JOptionPane;
import jdr.modele.Personnage;

/**
 *
 * @author matall
 */
public class MenuIdenCarac extends javax.swing.JFrame implements IdescriptionRace {

    private String race;
    private Personnage perso;
    private boolean b=true;
    private String choix;
    private int[] tabJet= {0,0,0,0,0,0};
    
    /**
     * Creates new form Menu
     */
    public MenuIdenCarac(Personnage p) {
        this.perso=p;
        this.race = p.getRace().getNom();
        
          
        initComponents();
       
        jLabelRace.setText(race);
        //cette boucle sert à mettre les bonus raciaux sur le menu
         for (int i = 0; i < NOMRACE.length; i++) {
            if(NOMRACE[i].equalsIgnoreCase(race)){
                jLabelBonusforce3.setText(Integer.toString(BONUSRACIAUX[i][0]));
                jLabelBonusDext2.setText(Integer.toString(BONUSRACIAUX[i][1]));
                jLabelconst2.setText(Integer.toString(BONUSRACIAUX[i][2]));
                jLabelBonusIntel2.setText(Integer.toString(BONUSRACIAUX[i][3]));
                jLabelSagesse2.setText(Integer.toString(BONUSRACIAUX[i][4]));
                jLabelBonuscharisme2.setText(Integer.toString(BONUSRACIAUX[i][0]));
            } 
            
          }
        //appelle de la méthode afin de savoir si les checkbox
        //du choix du bonus peuvent être affichées
        this.verifierRaceBonus();
    }
    
      public MenuIdenCarac() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNom = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jSexe = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JIdentite = new javax.swing.JLabel();
        jAge = new javax.swing.JLabel();
        jTextAge = new javax.swing.JTextField();
        jPoids = new javax.swing.JLabel();
        JTextPoids = new javax.swing.JTextField();
        jTaille = new javax.swing.JLabel();
        JtextTaille = new javax.swing.JTextField();
        jYeux = new javax.swing.JLabel();
        jTextYeux = new javax.swing.JTextField();
        jCheveux = new javax.swing.JLabel();
        JTexteCheveux = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextePeau = new javax.swing.JTextField();
        jDextrie = new javax.swing.JLabel();
        Jcentre = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jJet1 = new javax.swing.JLabel();
        jCaracteristique = new javax.swing.JLabel();
        jButtonForce = new javax.swing.JButton();
        jLabelJetForce = new javax.swing.JLabel();
        jJet2 = new javax.swing.JLabel();
        jLabelJetDext = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jJet3 = new javax.swing.JLabel();
        jLabelActioncomponent = new javax.swing.JLabel();
        jDeConstitution = new javax.swing.JButton();
        jJet4 = new javax.swing.JLabel();
        JLabelLancerIntel = new javax.swing.JLabel();
        jButtonDe = new javax.swing.JButton();
        jJet5 = new javax.swing.JLabel();
        jLabelTexteSagesse = new javax.swing.JLabel();
        jButtonDeSag = new javax.swing.JButton();
        jJet6 = new javax.swing.JLabel();
        jLabelTexteCharisme = new javax.swing.JLabel();
        jButtonDeSagesse = new javax.swing.JButton();
        jButtonValide = new javax.swing.JButton();
        JButtonAnnuler = new javax.swing.JButton();
        jLabelBonus = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelbonusForce1 = new javax.swing.JLabel();
        jLabelBonusDexterite = new javax.swing.JLabel();
        jLabelBonusConstitution = new javax.swing.JLabel();
        jLabelBonusIntel = new javax.swing.JLabel();
        jLabelBonusSagesse = new javax.swing.JLabel();
        jLabelbonuscharisme = new javax.swing.JLabel();
        jButtonToutLancer = new javax.swing.JButton();
        jCheckBoxforce = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabelRace = new javax.swing.JLabel();
        jLabelBonusforce2 = new javax.swing.JLabel();
        jLabelBonusforce3 = new javax.swing.JLabel();
        jLabelBonusDext2 = new javax.swing.JLabel();
        jLabelconst2 = new javax.swing.JLabel();
        jLabelBonusIntel2 = new javax.swing.JLabel();
        jLabelSagesse2 = new javax.swing.JLabel();
        jLabelBonuscharisme2 = new javax.swing.JLabel();
        jCheckBoxDext = new javax.swing.JCheckBox();
        jCheckBoxconstitution = new javax.swing.JCheckBox();
        jCheckBoxIntel = new javax.swing.JCheckBox();
        jCheckBoxSagesse = new javax.swing.JCheckBox();
        jCheckBoxcharisme = new javax.swing.JCheckBox();
        jComboBoxsexe = new javax.swing.JComboBox<>();
        jComboBoxdextrie = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondMenu.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 0, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Création de personnage");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 696, 95));

        jNom.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jNom.setForeground(new java.awt.Color(102, 102, 0));
        jNom.setText("Nom");
        jPanel2.add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 191, -1, -1));

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });
        jPanel2.add(jTextNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 189, 130, -1));

        jSexe.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jSexe.setForeground(new java.awt.Color(102, 102, 0));
        jSexe.setText("Sexe");
        jPanel2.add(jSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 221, 26, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 489, 208, 101));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 168, 208, 10));

        JIdentite.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        JIdentite.setForeground(new java.awt.Color(102, 102, 0));
        JIdentite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JIdentite.setText("Identité");
        jPanel2.add(JIdentite, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 131, 208, -1));

        jAge.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jAge.setForeground(new java.awt.Color(102, 102, 0));
        jAge.setText("Age");
        jPanel2.add(jAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 251, -1, -1));
        jPanel2.add(jTextAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 249, 130, -1));

        jPoids.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jPoids.setForeground(new java.awt.Color(102, 102, 0));
        jPoids.setText("Poids");
        jPanel2.add(jPoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 280, -1, -1));
        jPanel2.add(JTextPoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 279, 130, -1));

        jTaille.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jTaille.setForeground(new java.awt.Color(102, 102, 0));
        jTaille.setText("Taille (cm)");
        jPanel2.add(jTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 311, -1, -1));

        JtextTaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextTailleActionPerformed(evt);
            }
        });
        jPanel2.add(JtextTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 309, 130, -1));

        jYeux.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jYeux.setForeground(new java.awt.Color(102, 102, 0));
        jYeux.setText("Yeux");
        jPanel2.add(jYeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 337, -1, -1));
        jPanel2.add(jTextYeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 335, 130, -1));

        jCheveux.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jCheveux.setForeground(new java.awt.Color(102, 102, 0));
        jCheveux.setText("Cheveux");
        jPanel2.add(jCheveux, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 367, -1, -1));
        jPanel2.add(JTexteCheveux, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 365, 130, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Type De Peau");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 397, -1, -1));
        jPanel2.add(jTextePeau, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 395, 130, -1));

        jDextrie.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jDextrie.setForeground(new java.awt.Color(102, 102, 0));
        jDextrie.setText("Dextrie");
        jPanel2.add(jDextrie, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 427, -1, -1));

        Jcentre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Valeros.jpg"))); // NOI18N
        jPanel2.add(Jcentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 236, 322));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 168, 710, 10));

        jJet1.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet1.setForeground(new java.awt.Color(102, 102, 0));
        jJet1.setText("jet 1");
        jPanel2.add(jJet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jCaracteristique.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jCaracteristique.setForeground(new java.awt.Color(102, 102, 0));
        jCaracteristique.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCaracteristique.setText("Caractéristiques");
        jPanel2.add(jCaracteristique, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 247, 42));

        jButtonForce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jButtonForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForceActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonForce, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        jLabelJetForce.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelJetForce.setForeground(new java.awt.Color(102, 102, 0));
        jLabelJetForce.setText("<lancer le dé>");
        jPanel2.add(jLabelJetForce, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 80, -1));

        jJet2.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet2.setForeground(new java.awt.Color(102, 102, 0));
        jJet2.setText("jet 2");
        jPanel2.add(jJet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabelJetDext.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelJetDext.setForeground(new java.awt.Color(102, 102, 0));
        jLabelJetDext.setText("<lancer le dé>");
        jPanel2.add(jLabelJetDext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 78, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jJet3.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet3.setForeground(new java.awt.Color(102, 102, 0));
        jJet3.setText("jet 3");
        jPanel2.add(jJet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabelActioncomponent.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelActioncomponent.setForeground(new java.awt.Color(102, 102, 0));
        jLabelActioncomponent.setText("<lancer le dé>");
        jPanel2.add(jLabelActioncomponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 81, -1));

        jDeConstitution.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jDeConstitution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jDeConstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeConstitutionActionPerformed(evt);
            }
        });
        jPanel2.add(jDeConstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jJet4.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet4.setForeground(new java.awt.Color(102, 102, 0));
        jJet4.setText("jet 4");
        jPanel2.add(jJet4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        JLabelLancerIntel.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        JLabelLancerIntel.setForeground(new java.awt.Color(102, 102, 0));
        JLabelLancerIntel.setText("<lancer le dé>");
        jPanel2.add(JLabelLancerIntel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jButtonDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jButtonDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jJet5.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet5.setForeground(new java.awt.Color(102, 102, 0));
        jJet5.setText("jet 5");
        jPanel2.add(jJet5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabelTexteSagesse.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelTexteSagesse.setForeground(new java.awt.Color(102, 102, 0));
        jLabelTexteSagesse.setText("<Lancer le dé>");
        jPanel2.add(jLabelTexteSagesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jButtonDeSag.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jButtonDeSag.setForeground(new java.awt.Color(102, 102, 0));
        jButtonDeSag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jButtonDeSag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeSagActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeSag, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        jJet6.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jJet6.setForeground(new java.awt.Color(102, 102, 0));
        jJet6.setText("Jet 6");
        jPanel2.add(jJet6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabelTexteCharisme.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelTexteCharisme.setForeground(new java.awt.Color(102, 102, 0));
        jLabelTexteCharisme.setText("<lancer le dé>");
        jPanel2.add(jLabelTexteCharisme, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        jButtonDeSagesse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/de.png"))); // NOI18N
        jButtonDeSagesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeSagesseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeSagesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        jButtonValide.setText("Valider");
        jButtonValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValideActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonValide, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 130, 50));

        JButtonAnnuler.setText("Annuler");
        JButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(JButtonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 140, 50));

        jLabelBonus.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabelBonus.setForeground(new java.awt.Color(102, 102, 0));
        jLabelBonus.setText("Bonus");
        jPanel2.add(jLabelBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 40, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        jLabelbonusForce1.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabelbonusForce1.setForeground(new java.awt.Color(102, 102, 0));
        jLabelbonusForce1.setText("Force : ");
        jPanel2.add(jLabelbonusForce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 60, 20));

        jLabelBonusDexterite.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelBonusDexterite.setForeground(new java.awt.Color(102, 102, 0));
        jLabelBonusDexterite.setText("Dextérité : ");
        jPanel2.add(jLabelBonusDexterite, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 60, 20));

        jLabelBonusConstitution.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelBonusConstitution.setForeground(new java.awt.Color(102, 102, 0));
        jLabelBonusConstitution.setText("constitution : ");
        jPanel2.add(jLabelBonusConstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 80, 20));

        jLabelBonusIntel.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelBonusIntel.setForeground(new java.awt.Color(102, 102, 0));
        jLabelBonusIntel.setText("Intelligence :");
        jPanel2.add(jLabelBonusIntel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 80, 20));

        jLabelBonusSagesse.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelBonusSagesse.setForeground(new java.awt.Color(102, 102, 0));
        jLabelBonusSagesse.setText("Sagesse  :");
        jPanel2.add(jLabelBonusSagesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 80, 20));

        jLabelbonuscharisme.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelbonuscharisme.setForeground(new java.awt.Color(102, 102, 0));
        jLabelbonuscharisme.setText("charisme :");
        jPanel2.add(jLabelbonuscharisme, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 80, 20));

        jButtonToutLancer.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jButtonToutLancer.setForeground(new java.awt.Color(102, 102, 0));
        jButtonToutLancer.setText("Lancer toutes les jets de caractéristiques");
        jButtonToutLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToutLancerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonToutLancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 463, 390, 40));

        jCheckBoxforce.setText("choisir");
        jCheckBoxforce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxforceActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxforce, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("Pour la race : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jComboBox1.setToolTipText("");
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 90, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 90, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 90, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 90, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 90, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Force", "Dexterite", "Constitution", "Intelligence", "Sagesse", "charisme" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 90, -1));

        jLabelRace.setText("jLabel6");
        jPanel2.add(jLabelRace, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, -1, -1));

        jLabelBonusforce2.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabelBonusforce2.setForeground(new java.awt.Color(102, 102, 0));
        jPanel2.add(jLabelBonusforce2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, -1, -1));

        jLabelBonusforce3.setText("<stat>");
        jPanel2.add(jLabelBonusforce3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, -1));

        jLabelBonusDext2.setText("<stat>");
        jPanel2.add(jLabelBonusDext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, -1, -1));

        jLabelconst2.setText("<stat>");
        jPanel2.add(jLabelconst2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, -1, -1));

        jLabelBonusIntel2.setText("<stat>");
        jPanel2.add(jLabelBonusIntel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, -1, -1));

        jLabelSagesse2.setText("<stat>");
        jPanel2.add(jLabelSagesse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, -1, -1));

        jLabelBonuscharisme2.setText("<stat>");
        jPanel2.add(jLabelBonuscharisme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, -1));

        jCheckBoxDext.setText("choisir");
        jCheckBoxDext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDextActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxDext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 233, -1, 40));

        jCheckBoxconstitution.setText("choisir");
        jCheckBoxconstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxconstitutionActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxconstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, -1, 30));

        jCheckBoxIntel.setText("choisir");
        jCheckBoxIntel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIntelActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxIntel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, -1, 30));

        jCheckBoxSagesse.setText("choisir");
        jCheckBoxSagesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSagesseActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxSagesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, -1));

        jCheckBoxcharisme.setText("choisir");
        jCheckBoxcharisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxcharismeActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxcharisme, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        jComboBoxsexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        jPanel2.add(jComboBoxsexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 120, -1));

        jComboBoxdextrie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaucher", "Droite", "Ambidextre" }));
        jPanel2.add(jComboBoxdextrie, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 430, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // les actions perfomed suivant servent à faire disparaite
    //les autres checkbox que celle séléctionné afin d'empêcher 
    //le choix de plusieurs checkbox
    private void jCheckBoxcharismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxcharismeActionPerformed
        // TODO add your handling code here:

        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix = "charisme";
        this.jCheckBoxDext.setVisible(b);
        this.jCheckBoxIntel.setVisible(b);
        this.jCheckBoxSagesse.setVisible(b);
        this.jCheckBoxconstitution.setVisible(b);
        this.jCheckBoxforce.setVisible(b);

    }//GEN-LAST:event_jCheckBoxcharismeActionPerformed

    private void jCheckBoxSagesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSagesseActionPerformed
        // TODO add your handling code here:
        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix = "Sagesse";
        this.jCheckBoxDext.setVisible(b);
        this.jCheckBoxIntel.setVisible(b);
        this.jCheckBoxforce.setVisible(b);
        this.jCheckBoxconstitution.setVisible(b);
        this.jCheckBoxcharisme.setVisible(b);

    }//GEN-LAST:event_jCheckBoxSagesseActionPerformed

    private void jCheckBoxIntelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIntelActionPerformed
        // TODO add your handling code here:

        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix ="Intelligence";
        this.jCheckBoxDext.setVisible(b);
        this.jCheckBoxforce.setVisible(b);
        this.jCheckBoxSagesse.setVisible(b);
        this.jCheckBoxconstitution.setVisible(b);
        this.jCheckBoxcharisme.setVisible(b);

    }//GEN-LAST:event_jCheckBoxIntelActionPerformed

    private void jCheckBoxconstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxconstitutionActionPerformed
        // TODO add your handling code here:
        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix = "Constitution";
        this.jCheckBoxDext.setVisible(b);
        this.jCheckBoxIntel.setVisible(b);
        this.jCheckBoxSagesse.setVisible(b);
        this.jCheckBoxforce.setVisible(b);
        this.jCheckBoxcharisme.setVisible(b);

    }//GEN-LAST:event_jCheckBoxconstitutionActionPerformed

    private void jCheckBoxDextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDextActionPerformed
        // TODO add your handling code here:
        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix = "Dexterite";
        this.jCheckBoxforce.setVisible(b);
        this.jCheckBoxIntel.setVisible(b);
        this.jCheckBoxSagesse.setVisible(b);
        this.jCheckBoxconstitution.setVisible(b);
        this.jCheckBoxcharisme.setVisible(b);

    }//GEN-LAST:event_jCheckBoxDextActionPerformed

    private void jCheckBoxforceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxforceActionPerformed
        // TODO add your handling code here:

        if(b){
            this.b=false;
        }else{
            this.b=true;
        }
        choix = "Force";
        this.jCheckBoxDext.setVisible(b);
        this.jCheckBoxIntel.setVisible(b);
        this.jCheckBoxSagesse.setVisible(b);
        this.jCheckBoxconstitution.setVisible(b);
        this.jCheckBoxcharisme.setVisible(b);

    }//GEN-LAST:event_jCheckBoxforceActionPerformed

    private void jButtonToutLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToutLancerActionPerformed
        // TODO add your handling code here:
        jLabelJetForce.setText(String.valueOf(this.LancerDeCarac()));
        jLabelJetDext.setText(String.valueOf(this.LancerDeCarac()));
        jLabelActioncomponent.setText(String.valueOf(this.LancerDeCarac()));
        JLabelLancerIntel.setText(String.valueOf(this.LancerDeCarac()));
        jLabelTexteSagesse.setText(String.valueOf(this.LancerDeCarac()));
        jLabelTexteCharisme.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButtonToutLancerActionPerformed

    private void JButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAnnulerActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JButtonAnnulerActionPerformed

    private void jButtonValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValideActionPerformed
        // TODO add your handling code here:µ
          boolean toutbon = true;
        try {
             

      
        if(this.jTextNom.getText() != null){
            perso.setNom(this.jTextNom.getText());
        }else{
            toutbon=false;
        }
        perso.setSexe(this.jComboBoxsexe.getSelectedItem().toString());

        if(this.jTextAge!= null){
          perso.setAge(Integer.parseInt(this.jTextAge.getText()));
        }else{
            toutbon = false;
        }

        if(this.JTextPoids!= null){
            perso.setPoids(Integer.parseInt(this.JTextPoids.getText()));
        }else{
            toutbon = false;
        }

        if(this.JtextTaille != null){
            perso.setTaille(Integer.parseInt(this.JtextTaille.getText()));
        }else{
            toutbon = false;
        }

        if(this.jTextYeux!= null){
            perso.setYeux((this.jTextYeux.getText()));
        }else{
            toutbon = false;
        }

        if(this.JTexteCheveux!= null){
            perso.setCheveux((this.JTexteCheveux.getText()));
        }else{
            toutbon = false;
        }

        if(this.jTextePeau != null){
            perso.setTypePeau((this.jTextePeau.getText()));
        }else{
            toutbon = false;
        }
        
         perso.setDextrie(this.jComboBoxdextrie.getSelectedItem().toString());
         
        for (int i = 0; i < NOMSTAT.length; i++) {
            if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
               
                tabJet[i]= Integer.parseInt(this.jLabelJetForce.getText());
            }
            
             if(this.jComboBox2.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
                tabJet[i]= Integer.parseInt(this.jLabelJetDext.getText());
            }
             
              if(this.jComboBox3.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
                tabJet[i]= Integer.parseInt(this.jLabelActioncomponent.getText());
            }
              
               if(this.jComboBox4.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
                tabJet[i]= Integer.parseInt(this.JLabelLancerIntel.getText());
            }
               
             if(this.jComboBox5.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
                tabJet[i]= Integer.parseInt(this.jLabelTexteSagesse.getText());
            }
             
              if(this.jComboBox6.getSelectedItem().toString().equalsIgnoreCase(NOMSTAT[i])){
                tabJet[i]= Integer.parseInt(this.jLabelTexteCharisme.getText());
            }
        }
        
        for (int i = 0; i <  tabJet.length; i++) {
          if(tabJet[i] == 0){
             toutbon =false; 
          }
          if(choix !=null){
               for (int j = 0; j < NOMSTAT.length; j++) {
                if(choix.equalsIgnoreCase(NOMSTAT[j])){
                    tabJet[i]= tabJet[i] +2;
                }
                
            }
          }
         }  
         tabJet[0]= tabJet[0]+ Integer.parseInt(this.jLabelBonusforce3.getText());
         tabJet[1]= tabJet[1]+ Integer.parseInt(this.jLabelBonusDext2.getText());
         tabJet[2]= tabJet[2]+ Integer.parseInt(this.jLabelconst2.getText());
         tabJet[3]= tabJet[3]+ Integer.parseInt(this.jLabelBonusIntel2.getText()); 
         tabJet[4]= tabJet[4]+ Integer.parseInt(this.jLabelSagesse2.getText()); 
         tabJet[5]= tabJet[5]+ Integer.parseInt(this.jLabelBonuscharisme2.getText()); 

         perso.setForce(tabJet[0]);
         perso.setDexterite(tabJet[1]);
         perso.setConstitution(tabJet[2]);
         perso.setIntelligence(tabJet[3]);
         perso.setSagesse(tabJet[4]);
         perso.setCharisme(tabJet[5]);
         
          if(toutbon){
             System.out.println("jdr.vue.MenuIdenCarac.jButtonValideActionPerformed()"+perso);
              MenClasse suite=  new MenClasse(perso);
               
               suite.setVisible(true);
               this.dispose();
         }
         else{
              JOptionPane.showMessageDialog(null,
                        "Veuillez vérifier vos champs",
                        "ALERTE", JOptionPane.ERROR_MESSAGE);
         }
        } catch (Exception e) {
          
           }
       
    }//GEN-LAST:event_jButtonValideActionPerformed

    private void jButtonDeSagesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeSagesseActionPerformed
        // TODO add your handling code here:

        jLabelTexteCharisme.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButtonDeSagesseActionPerformed

    private void jButtonDeSagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeSagActionPerformed
        // TODO add your handling code here:
        jLabelTexteSagesse.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButtonDeSagActionPerformed

    private void jButtonDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeActionPerformed
        // TODO add your handling code here:

        JLabelLancerIntel.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButtonDeActionPerformed

    private void jDeConstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeConstitutionActionPerformed
        // TODO add your handling code here:
        jLabelActioncomponent.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jDeConstitutionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabelJetDext.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForceActionPerformed
        // TODO add your handling code here:

        jLabelJetForce.setText(String.valueOf(this.LancerDeCarac()));
    }//GEN-LAST:event_jButtonForceActionPerformed

    private void JtextTailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextTailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextTailleActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed
    //cette méthode fera apparaitre les checkbox si
    //la race choisi peut choisir où mettre son bonus
    private boolean verifierRaceBonus(){
        if(race.equalsIgnoreCase("Demi-elfes")||
                race.equalsIgnoreCase("Demi-orques") ||
                race.equalsIgnoreCase("Humains")){
            
            this.jCheckBoxDext.setVisible(true);
        this.jCheckBoxIntel.setVisible(true);
        this.jCheckBoxSagesse.setVisible(true);
        this.jCheckBoxconstitution.setVisible(true);
        this.jCheckBoxcharisme.setVisible(true);
         this.jCheckBoxforce.setVisible(true);
         
         
                 
                 }else{
            
              this.jCheckBoxDext.setVisible(false);
        this.jCheckBoxIntel.setVisible(false);
        this.jCheckBoxSagesse.setVisible(false);
        this.jCheckBoxconstitution.setVisible(false);
        this.jCheckBoxcharisme.setVisible(false);
         this.jCheckBoxforce.setVisible(false);
            
            
            
            return true;
        }
        
        return false; 
    }
   
    
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIdenCarac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIdenCarac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIdenCarac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIdenCarac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIdenCarac().setVisible(true);
            }
        });
    }
    
  
    
    private int LancerDeCarac (){
        //cette méthode retournera un jet de dé
        //qui a pour spécificité que sur les 4 jet 
        //le jet avec la valeur la plus faible sera retiré au total
        
        int jet1 =  (int)(Math.random()*6 +1);
        int jet2 =  (int)(Math.random()*6 +1);
        int jet3 =  (int)(Math.random()*6 +1);
        int jet4 =  (int)(Math.random()*6 +1);
       
        
         if ( jet1 > jet2 ){
             int temp;
             temp = jet1;
             jet1 =jet2;
             jet2=temp;
             
         }
         if ( jet1 > jet3 ){
             int temp;
             temp = jet1;
             jet1 =jet3;
             jet3=temp;
             
         }
         if ( jet1 > jet4 ){
             int temp;
             temp = jet1;
             jet1 =jet4;
             jet4=temp;
             
         }
         int jettotal = jet2+jet3 +jet4 ;
          return jettotal;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAnnuler;
    private javax.swing.JLabel JIdentite;
    private javax.swing.JLabel JLabelLancerIntel;
    private javax.swing.JTextField JTextPoids;
    private javax.swing.JTextField JTexteCheveux;
    private javax.swing.JLabel Jcentre;
    private javax.swing.JTextField JtextTaille;
    private javax.swing.JLabel jAge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDe;
    private javax.swing.JButton jButtonDeSag;
    private javax.swing.JButton jButtonDeSagesse;
    private javax.swing.JButton jButtonForce;
    private javax.swing.JButton jButtonToutLancer;
    private javax.swing.JButton jButtonValide;
    private javax.swing.JLabel jCaracteristique;
    private javax.swing.JCheckBox jCheckBoxDext;
    private javax.swing.JCheckBox jCheckBoxIntel;
    private javax.swing.JCheckBox jCheckBoxSagesse;
    private javax.swing.JCheckBox jCheckBoxcharisme;
    private javax.swing.JCheckBox jCheckBoxconstitution;
    private javax.swing.JCheckBox jCheckBoxforce;
    private javax.swing.JLabel jCheveux;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBoxdextrie;
    private javax.swing.JComboBox<String> jComboBoxsexe;
    private javax.swing.JButton jDeConstitution;
    private javax.swing.JLabel jDextrie;
    private javax.swing.JLabel jJet1;
    private javax.swing.JLabel jJet2;
    private javax.swing.JLabel jJet3;
    private javax.swing.JLabel jJet4;
    private javax.swing.JLabel jJet5;
    private javax.swing.JLabel jJet6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelActioncomponent;
    private javax.swing.JLabel jLabelBonus;
    private javax.swing.JLabel jLabelBonusConstitution;
    private javax.swing.JLabel jLabelBonusDext2;
    private javax.swing.JLabel jLabelBonusDexterite;
    private javax.swing.JLabel jLabelBonusIntel;
    private javax.swing.JLabel jLabelBonusIntel2;
    private javax.swing.JLabel jLabelBonusSagesse;
    private javax.swing.JLabel jLabelBonuscharisme2;
    private javax.swing.JLabel jLabelBonusforce2;
    private javax.swing.JLabel jLabelBonusforce3;
    private javax.swing.JLabel jLabelJetDext;
    private javax.swing.JLabel jLabelJetForce;
    private javax.swing.JLabel jLabelRace;
    private javax.swing.JLabel jLabelSagesse2;
    private javax.swing.JLabel jLabelTexteCharisme;
    private javax.swing.JLabel jLabelTexteSagesse;
    private javax.swing.JLabel jLabelbonusForce1;
    private javax.swing.JLabel jLabelbonuscharisme;
    private javax.swing.JLabel jLabelconst2;
    private javax.swing.JLabel jNom;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPoids;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jSexe;
    private javax.swing.JLabel jTaille;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextYeux;
    private javax.swing.JTextField jTextePeau;
    private javax.swing.JLabel jYeux;
    // End of variables declaration//GEN-END:variables
}
