/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdr.vue;

import controle.connexion.ControleConnexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import jdr.modele.Parametres;

/**
 *
 * @author mathi
 */
public class MenuConnexion extends javax.swing.JFrame {

    /**
     * Creates new form MenuConnexion
     */
    public MenuConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Connexion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 130));

        jLabelId.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 51));
        jLabelId.setText("Identifiant");
        jPanel1.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, 60));

        jTextFieldID.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jTextFieldID.setText("Entre votre Id ici");
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 300, 60));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 300, 50));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Mot De Passe");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 40));

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 150, 70));

        jButton2.setText("Annuler");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 350, 150, 70));

        jLabelfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fond.png"))); // NOI18N
        jPanel1.add(jLabelfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        JMenuPrincipale    laFenPrinc = new JMenuPrincipale();
        
        if(controleConnexion_Appel()){
            try {
                ControleConnexion.transfertDonnees();
            } catch (SQLException ex) {
                Logger.getLogger(MenuConnexion.class.getName()).log(Level.SEVERE, null, ex);
            }
            laFenPrinc.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private boolean controleConnexion_Appel() {
        // contrôle de la saisie
        Parametres p = new Parametres();
        String leNom = jTextFieldID.getText();
        String leMotDePasse = jPasswordField1.getText();
        
             boolean bControle = false;
        //String leMotDePasse = String.valueOf(jTxt_Password.getPassword());
       
        if (ControleConnexion.controle(leNom, leMotDePasse)) {
            if (ControleConnexion.isEtatConnexion()) {
                bControle = true;
            } else {
                JOptionPane.showMessageDialog(null,
                        "Impossible de se connecter"
                        + " à la base de données.\n\n"
                        + "Vos nom et mot de passe sont corrects.\n"
                        + "Mais les paramètres pour le pilote"
                        + " et la base de données "
                        + "doivent être vérifiés.\n\n"
                        + "Contacter le responsable informatique.",
                        "ALERTE", JOptionPane.ERROR_MESSAGE);
            }
        }
 
    
            
        
       
        return bControle;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelfond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
