/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdr.vue;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import jdr.modele.Personnage;

/**
 *
 * @author matall
 */
public class MenuRace extends javax.swing.JFrame implements IdescriptionRace{
String choix = RACEDESLIENS[0];
String choixBonus;
    /**
     * Creates new form MenuRace
     */
    public MenuRace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelFond = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelRaceTitre = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea("Demi-elfes. Les demi-elfes oscillent souvent entre les deux mondes de leurs parents et mêlent la grâce aux contradictions. Leur héritage dual et leurs dons naturels en font de brillants diplomates et de bons émissaires de la paix, mais ils se laissent souvent envahir par une immense mélancolie et s’isolent en comprenant qu’ils ne font ni partie de la société humaine ni de la société elfique.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(JLabelFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 0, -1, 623));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Demi-Elfes", "Demi-orques", "Elfes", "Gnomes", "Halfelins", "Humains", "Nains" }));
        jComboBox1.addActionListener(new ItemAction());
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 161, 59));

        jLabelRaceTitre.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        jLabelRaceTitre.setText("Choix de la Race");
        getContentPane().add(jLabelRaceTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 191, 56));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Demi-elfe.jpg"))); // NOI18N
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 460, 630));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 0, 10));

        jButton1.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jButton1.setText("Choisir cette Race");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 310, 80));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);
        jTextArea3.setLineWrap(true);
        jTextArea3.setWrapStyleWord(true);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          for (int i = 0; i < TABRACE.length; i++) {
           if(TABRACE[i].getNom()==choix){
               Personnage personnage = new Personnage();
               
               personnage.setRace(TABRACE[i]);
              
               MenuIdenCarac suite = new MenuIdenCarac(personnage);
               suite.setVisible(true);
               dispose();
               
           }
            
        }
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    /**d
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelFond;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelRaceTitre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

    
 class ItemAction implements ActionListener{
    public void actionPerformed(ActionEvent e) {
     //obtention de la chaine de caractéres séléctionnée
     choix = jComboBox1.getSelectedItem().toString();
       
         for (int i = 0; i < RACEDESLIENS.length; i++) {
           //on compare le tableau contenu dans l'interface
           //avec le choix
           if(RACEDESLIENS[i].equalsIgnoreCase(choix)){
               //on met la description en prenant l'indice d'après
               // dans le tableau
              jTextArea3.setText(RACEDESLIENS[i+1]);
              //on met l'image en mettant l'index +2
              jLabelImage.setIcon(new javax.swing.ImageIcon(getClass()
                      .getResource(RACEDESLIENS[i+2])));

                    
           }
            
        }
    }               
  }
}



